SELECT 'HD_CODE_COMM' TABLE_NAME, CNT FROM (SELECT TABLE_NAME, COUNT(1) CNT FROM VT_SCHEMA GROUP BY TABLE_NAME) 
WHERE TABLE_NAME(+) = 'HD_CODE_COMM' ;

 
    
WITH 
 SCHAME_DATA AS (
    SELECT TABLE_NAME, COUNT(1) CNT FROM VT_SCHEMA GROUP BY TABLE_NAME
)
,SRC_TABLE_DATA AS (
SELECT 'HD_CODE_ACNT'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_CODE_AGENCY'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_CODE_AGREE'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_CODE_COMM'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_CODE_COMPAMT'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_CODE_CUSTOMER_TXTUP'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_CODE_DEPOSIT'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_CODE_DEPT'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_CODE_DEPTMEMO'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_CODE_GIFT'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_CODE_HOUSE'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_CODE_OPTION'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_CODE_SIHANG'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_CODE_SPECIAL'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_APPLY'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_BANKETC'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_COMPAMT'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_CONSULT'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_DAY_INCOME'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_DAY_INCOME_ADJUST'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_DAY_INCOME_CONV'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_DISK_TEMP'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_ETCAMT'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_INCOME'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_INCOME_ADJUST'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_INCOME_BANK'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_INCOME_REIN'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_INCOME_TEMP'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_INDEMINITY'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_INDEMINITY_CONV'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_JESE'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_LEND'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_LEND_TXTUP'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_MAGAM'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_OPTION'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_RATE_DELAY'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_RATE_DISCOUNT'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_REMARK'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_RESERVE'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_SEALHISTORY'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_SELL'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_SELL_DAMO'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_SELL_TXTUP'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_SELLDETAIL'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_SELLDETAIL_DAMO'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_SELLDETAIL_TEMP'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_SLIP_MAGAM'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_SUBSCRIBE'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_SUBSCRIBE_TXTUP'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_SUPPLY'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_SUPPLY_CHANGE'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_SUPPLY_CONV'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_UNION'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_HOUS_VIRTURE'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_LEASE_BONDSEIZURE'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_REFER_GIFT'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_REFER_HOLIDAY'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_REFER_INCOMEBILL'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_REFER_INCOMEREMARK'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_REFER_KEY'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_REFER_MOVEIN'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_REFER_RATE_DELAY'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_REFER_RATE_DISCOUNT'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_REFER_SELLCREATE'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_REFER_SELLDETAIL'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_REFER_SQUARE'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_REFER_SQUARE_CNT'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_REFER_SQUARE_CONV'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_REFER_SQUAREDETAIL'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_REFER_SQUAREDETAIL_CNT'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_REFER_SQUAREDETAIL_CONV'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_RENT_CANCEL'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_RENT_DETAIL_RENT'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_RENT_DETAIL_TERM'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_RENT_DONGHO'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_RENT_ETC'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_RENT_FIXRATE'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_RENT_GIRO'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_RENT_GURT_AGREE'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_RENT_GURT_AGREE_ADJ'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_RENT_GURT_AGREE_TEMP'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_RENT_GURT_INCOME'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_RENT_GURT_INCOME_ADJ'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_RENT_GURT_INCOME_DAILY'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_RENT_GURT_INCOME_TEMP'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_RENT_MANAGEMENT'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_RENT_MANAGEMENT_CONV'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_RENT_MASTER'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_RENT_RATE_DELAY'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_RENT_RATE_DISCOUNT'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_RENT_REMARK'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_RENT_RENT_AGREE'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_RENT_RENT_AGREE_ADJ'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_RENT_RENT_AGREE_TEMP'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_RENT_RENT_INCOME'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_RENT_RENT_INCOME_ADJ'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_RENT_RENT_INCOME_DAILY'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_RENT_RENT_INCOME_TEMP'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_SALE_ETC'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_SALE_INCOME_UNKNOWN'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_SUPPLY_CONV'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_TAX_CALCULATE'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_TAX_CALCULATE_AGREE'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_TAX_CALCULATE_REAL'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HD_VIRTURE_ACCOUNT'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'VW_HD_CODE_CUSTOMER'  AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'VW_HD_HOUS_SELL'   AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'AM_CODE_VALIDATION' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'CB3_CVS_DATA' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HR_ORDE_MASTER' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'HR_PERS_MASTER' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'MM_COMM_CONTRACT' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'MM_PROJ_ACNTCODE' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'MM_PROJ_CODE_DETAIL' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'SM_AUTH_PROJECT' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'SM_AUTH_USER' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'SM_CODE_BANK_HEAD' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'SM_CODE_CALENDAR' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'SM_CODE_COMPANY' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'SM_CODE_CUST' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'SM_CODE_DEPT' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'SM_CODE_PROJECT' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'SM_CODE_VALID_MAST' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'SM_CODE_VALIDATION' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'SM_TRANS_CB3_CVS_DATA' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'SM_TRANS_CMS' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'SM_TRANS_GIRO' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'SM_TRANS_VIRTURE_DEPOSIT' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'TM_CODE_ACNT' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'TM_CODE_BANK' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'TM_CODE_CUST_ACNT' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'TM_CODE_DEPOSIT' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'TM_CODE_DEPT' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'TM_ENDX_HIS_DAY' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'TM_SLIP_DETAIL' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'TM_SLIP_MASTER' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'TM_WORK_WORKDEPTNO' AS SRC_TABLE_NAME FROM DUAL UNION
SELECT 'TM_WORK_WORKNO' AS SRC_TABLE_NAME FROM DUAL
)
SELECT 
    SCHAME_DATA.TABLE_NAME 
    ,
    SRC_TABLE_DATA.SRC_TABLE_NAME
FROM 
    SRC_TABLE_DATA
    ,SCHAME_DATA
WHERE     
     SRC_TABLE_DATA.SRC_TABLE_NAME = SCHAME_DATA.TABLE_NAME(+)
;

