DROP VIEW KAIT_TST.VW_HD_CODE_CUSTOMER;

/* Formatted on 2017-06-07 오전 9:24:53 (QP5 v5.115.810.9015) */
CREATE OR REPLACE FORCE VIEW VW_HD_CODE_CUSTOMER
(
   CUST_CODE,
   CUST_NAME,
   CUSTCODE_TAG,
   CUST_LEGAL_NO,
   HANDPHONE,
   TEL,
   COMP_TEL,
   ZIP,
   ADDR1,
   ADDR2,
   OWNER,
   CONDITION,
   CATEGORY,
   EMAIL,
   RESIDENT_ZIP,
   RESIDENT_ADDR1,
   RESIDENT_ADDR2,
   USEYN,
   COMP_RECV_YN,
   HD_YN,
   DEPT_CODE,
   FOREIGN_TAG,
   FOREIGN_NATION,
   INPUT_DUTY_ID,
   INPUT_DATE,
   CHG_DUTY_ID,
   CHG_DATE
)
AS
   SELECT   cust_code,
            cust_name,
            cust_div AS custcode_tag,
            cust_legal_no,
            cellno AS handphone,
            phone AS tel,
            comp_phone AS comp_tel,                             --회사전화번호
            zip_code AS zip,
            addr1,
            addr2,
            represent_name AS owner,
            biz_status AS condition,
            biz_type AS CATEGORY,
            send_email AS email,
            send_zip_code AS resident_zip,
            send_addr1 AS resident_addr1,
            send_addr2 AS resident_addr2,
            use_yn AS useyn,
            info_yn AS comp_recv_yn,                        --회사정보수신여부
            hd_yn,
            proj_code,
            foreign_tag,
            --외국인인경우 코드종류- EX)여권번호, 시민번호등
            foreign_nation,                                         --국가코드
            input_duty_id,
            input_date,
            chg_duty_id,
            chg_date
     FROM   sm_code_cust
    WHERE   hd_yn = 'Y' AND use_yn = 'Y';


DROP VIEW VW_HD_HOUS_SELL;

/* Formatted on 2017-06-07 오전 9:25:27 (QP5 v5.115.810.9015) */
CREATE OR REPLACE FORCE VIEW VW_HD_HOUS_SELL
(
   CUST_CODE,
   SEQ,
   DEPT_CODE,
   HOUSETAG,
   BUILDNO,
   HOUSENO,
   DONGHO,
   CUST_NAME,
   SQUARE,
   TYPE,
   CLASS,
   OPTIONCODE,
   CONTRACTTAG,
   CONTRACTDATE,
   CONTRACTNO,
   LOAN_TAG,
   LEASETAG,
   LASTCHANGEDATE,
   CHANGETAG,
   CHANGEDATE,
   CANCEL_REASON,
   CHILD_BUILDNO,
   CHILD_HOUSENO,
   RELA_CUSTCODE,
   RELA_SEQ,
   VATTAG,
   EXCLUSIVEAREA,
   COMMONAREA,
   ETCCOMMONAREA,
   PARKINGAREA,
   SERVICEAREA,
   SITEAREA,
   MOVEINSTARTDATE,
   MOVEINENDDATE,
   UNION_CNT,
   REMARK,
   REFUNDMENTDATE,
   REFUNDMENTAMT,
   PENALTYAMT,
   LOAN_INTEREST,
   SODUK_TAX,
   JUMIN_TAX,
   BANK_LOAN_ORGAMT,
   BANK_LOAN_INTEREST,
   LOANBANK,
   LOANDEPOSIT,
   LOANUSER,
   REFUND_DEPOSIT,
   REFUND_BANK,
   COMP_LOANAMT,
   BILL_RETURNAMT,
   DELAY_INDEMINITY,
   DEPOSIT_COUNT,
   CO_CUSTCODE,
   CO_SANGHO,
   CO_CONDITION,
   CO_CATEGORY,
   CATEGORY_NAME,
   SLIPDATE,
   SLIPSEQ,
   INPUT_DUTY_ID,
   INPUT_DATE,
   CHG_DUTY_ID,
   CHG_DATE,
   PRTSQUARE,
   BANK_LOAN_INTEREST2,
   ETC_AMT,
   RENTHD_YN,
   RENTHD_SEQ,
   BALCONY_TAG,
   BALCONYAREA,
   DAYMONTH_TAG,
   FLOOR,
   CONT_CONDITION,
   LAND_RETURN,
   INT_CALC_DATE,
   PREDISAMT,
   PROXYAMT,
   INCONT_DATE,
   TRUSTAMT,
   PREDIS_TAG,
   PROXY_TAG,
   TRUST_TAG,
   VIR_YN,
   VDEPOSIT
)
AS
   SELECT   A.CUST_CODE,
            A.SEQ,
            A.DEPT_CODE,
            A.HOUSETAG,
            A.BUILDNO,
            A.HOUSENO,
            A.DONGHO,
            A.CUST_NAME,
            A.SQUARE,
            A.TYPE,
            A.CLASS,
            A.OPTIONCODE,
            A.CONTRACTTAG,
            LEAST (A.CONTRACTDATE, NVL (B.RECEIPTDATE, '99999999')),
            A.CONTRACTNO,
            A.LOAN_TAG,
            A.LEASETAG,
            CASE
               WHEN A.CONTRACTDATE = A.LASTCHANGEDATE
               THEN
                  LEAST (A.CONTRACTDATE, NVL (B.RECEIPTDATE, '99999999'))
               ELSE
                  A.LASTCHANGEDATE
            END,
            A.CHANGETAG,
            A.CHANGEDATE,
            A.CANCEL_REASON,
            A.CHILD_BUILDNO,
            A.CHILD_HOUSENO,
            A.RELA_CUSTCODE,
            A.RELA_SEQ,
            A.VATTAG,
            A.EXCLUSIVEAREA,
            A.COMMONAREA,
            A.ETCCOMMONAREA,
            A.PARKINGAREA,
            A.SERVICEAREA,
            A.SITEAREA,
            A.MOVEINSTARTDATE,
            A.MOVEINENDDATE,
            A.UNION_CNT,
            A.REMARK,
            A.REFUNDMENTDATE,
            A.REFUNDMENTAMT,
            A.PENALTYAMT,
            A.LOAN_INTEREST,
            A.SODUK_TAX,
            A.JUMIN_TAX,
            A.BANK_LOAN_ORGAMT,
            A.BANK_LOAN_INTEREST,
            A.LOANBANK,
            A.LOANDEPOSIT,
            A.LOANUSER,
            A.REFUND_DEPOSIT,
            A.REFUND_BANK,
            A.COMP_LOANAMT,
            A.BILL_RETURNAMT,
            A.DELAY_INDEMINITY,
            A.DEPOSIT_COUNT,
            A.CO_CUSTCODE,
            A.CO_SANGHO,
            A.CO_CONDITION,
            A.CO_CATEGORY,
            A.CATEGORY_NAME,
            A.SLIPDATE,
            A.SLIPSEQ,
            A.INPUT_DUTY_ID,
            A.INPUT_DATE,
            A.CHG_DUTY_ID,
            A.CHG_DATE,
            A.PRTSQUARE,
            A.BANK_LOAN_INTEREST2,
            A.ETC_AMT,
            A.RENTHD_YN,
            A.RENTHD_SEQ,
            A.BALCONY_TAG,
            A.BALCONYAREA,
            A.DAYMONTH_TAG,
            A.FLOOR,
            A.CONT_CONDITION,
            A.LAND_RETURN,
            A.INT_CALC_DATE,
            A.PREDISAMT,
            A.PROXYAMT,
            A.INCONT_DATE,
            A.TRUSTAMT,
            A.PREDIS_TAG,
            A.PROXY_TAG,
            A.TRUST_TAG,
            A.VIR_YN,
            A.VDEPOSIT
     FROM   HD_HOUS_SELL A,
            (  SELECT   CUST_CODE,
                        SEQ,
                        NVL (MIN (RECEIPTDATE), '99999999') AS RECEIPTDATE
                 FROM   HD_HOUS_INCOME
             GROUP BY   CUST_CODE, SEQ) B
    WHERE   A.CUST_CODE = B.CUST_CODE(+) AND A.SEQ = B.SEQ(+);

DROP VIEW VW_HD_HOUS_SELLDETAIL;

/* Formatted on 2017-06-07 오전 9:25:52 (QP5 v5.115.810.9015) */
CREATE OR REPLACE FORCE VIEW VW_HD_HOUS_SELLDETAIL
(
   CUST_CODE,
   SEQ,
   COUNTS,
   DEPT_CODE,
   HOUSETAG,
   BUILDNO,
   HOUSENO,
   AGREEDATE,
   ORG_AGREEDATE,
   LANDAMT,
   BUILDAMT,
   VATAMT,
   BUNAMT,
   DC_YN,
   AC_YN,
   PERPECTTAG,
   RECEIPTAMT,
   DISTRIBUTE_RATE,
   SLIPDT,
   SLIPSEQ,
   INPUT_DUTY_ID,
   INPUT_DATE,
   CHG_DUTY_ID,
   CHG_DATE,
   MANAGEAMT
)
AS
   SELECT   A.CUST_CODE,
            A.SEQ,
            A.COUNTS,
            A.DEPT_CODE,
            A.HOUSETAG,
            A.BUILDNO,
            A.HOUSENO,
            CASE
               WHEN A.COUNTS = '90'
                    AND NVL (B.MOVEINENDDATE, '00000000') > A.AGREEDATE
               THEN
                  B.MOVEINENDDATE
               ELSE
                  A.AGREEDATE
            END
               AS AGREEDATE,
            A.AGREEDATE AS ORG_AGREEDATE,
            A.LANDAMT,
            A.BUILDAMT,
            A.VATAMT,
            A.BUNAMT,
            A.DC_YN,
            A.AC_YN,
            A.PERPECTTAG,
            A.RECEIPTAMT,
            A.DISTRIBUTE_RATE,
            A.SLIPDT,
            A.SLIPSEQ,
            A.INPUT_DUTY_ID,
            A.INPUT_DATE,
            A.CHG_DUTY_ID,
            A.CHG_DATE,
            A.MANAGEAMT
     FROM   HD_HOUS_SELLDETAIL A, HD_HOUS_SELL B
    WHERE   A.CUST_CODE = B.CUST_CODE AND A.SEQ = B.SEQ;

